import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const  videos = [
  { _id: uuid(),
    categoryName: "Sweet Dish",
    creator: "Hebbars Kitchen",
    videoUrl:"https://www.youtube.com/watch?v=ZcnEDtJgTX8",
    thumbnailUrl: "https://img.youtube.com/vi/ZcnEDtJgTX8/maxresdefault.jpg",
    title: "Mohanthal Sweet Mithai Recipe - Halwai Style | Danedar Besan Sweet - Traditional Gujurat Sweet",
    logoUrl:"https://yt3.ggpht.com/ytc/AKedOLSCB7LCbVXfDVLCFuphDPHfboJ0emo3TGaRtuuV=s88-c-k-c0x00ffffff-no-rj" ,
    videoId:"ZcnEDtJgTX8",
    description:"mohanthal recipe | halwai style mohanthal sweet | mohanthal mithai with detailed photo and video recipe. a traditional and authentic besan flour-based sweet recipe known for its creamy and richness. it is a popular besan based barfi recipe from the state of gujarat and is prepared especially during the festival season and occasion. it shares the same shape and texture of a besan barfi, yet it does carry its own unique and creamy taste in each bite."},
 
     {  _id: uuid(),
      categoryName: "Ice Cream",
      creator: "Chef Ranveer Brar",
      videoUrl:"https://www.youtube.com/watch?v=DGFAltVowvo",
      thumbnailUrl: "https://img.youtube.com/vi/DGFAltVowvo/maxresdefault.jpg",
      title: "Eggless Ice Cream | तीन चीजों से मनपसंद आइस क्रीम | Bonus Condensed Milk recipe | Chef Ranveer",
      logoUrl:"https://yt3.ggpht.com/uv-y2lYaj1Kfz-LuQwSn_vesLvbrZz_EKAo7KIat5Eb1M6LOFn6fkcZIpW3YibOJoldqKseCiw=s88-c-k-c0x00ffffff-no-rj" ,
      videoId:"DGFAltVowvo",
      description:"Process For Condensed Milk In a sauce pot, add milk, sugar and mix it well. Cook on medium flame for 5 minutes. In a bowl mix milk powder, baking soda and then transfer this mixture into the sauce pot. Keep stirring continuously on medium flame. The mixture will start to thicken slightly.After 3 minutes, the mixture will turn into a frothy and silky smooth texture.Now turn off the flame and let it cool completely. make sure to turn off the flame when the mixture is slightly Thin. as it thickens once cooled completely."},
    {  _id: uuid(),
      categoryName: "Ice Cream",
      creator: "Masala Kitchen",
      videoUrl:"https://www.youtube.com/watch?v=N6m6JgimUSg",
      thumbnailUrl: "https://img.youtube.com/vi/N6m6JgimUSg/maxresdefault.jpg",
      title: "सिर्फ 1/2 litre दूध से बाजार जैसी क्रीमी आइसक्रीम बनाये बिना झंझट | Homemade Custard Ice Cream |",
      logoUrl:"https://yt3.ggpht.com/DaVa0ac-SAt3ELNHClQioSOJb-OB6TCV-MtZUQOfmbsw7gYC2hT308oBZyhBjP97oqxBDXSigg=s88-c-k-c0x00ffffff-no-rj" ,
      videoId:"N6m6JgimUSg",
      description:"आज मसाला किचन में हम लाये है कस्टर्ड आइस क्रीम की रेसिपी | कस्टर्ड आइस क्रीम अब आप बना सकते है घर पर वो भी बहुत आसानी से और कम सामान के साथ | एक बार ये कस्टर्ड आइस क्रीम इस तरीके से आपने बना ली तो बाजार की आइस क्रीम भूल जाओगे | यह मैंगो आइस क्रीम अगर इस तरीके से बनाएंगे तो फ़र्क़ बता ही नहीं पाएंगे की बाजार की कौन सी है और घर की कौन सी है | यह कस्टर्ड आइस क्रीम अगर आपने घर में बना ली तो बच्चे खुश हो जायेंगे | कस्टर्ड आइस क्रीम बनाने का आसान तरीका, मैंगो आइस क्रीम बनाने का आसान तरीका और भी कई आइस क्रीम बनाने का आसान तरीका आप देख सकते है मसाला किचन की आइस क्रीम रेसिपी में देख सकते है | मसाला किचन | पूनम देवनानी रेसिपीज | "},
    {  _id: uuid(),
      categoryName: "Ice Cream",
      creator: "Aliza In The Kitchen",
      videoUrl:"https://www.youtube.com/watch?v=qksZcqogaLQ",
      thumbnailUrl: "https://img.youtube.com/vi/qksZcqogaLQ/maxresdefault.jpg",
      title: "Homemade Vanilla Ice Cream Recipe (Only 3 Ingredients) | No Eggs | No Ice Cream Machine",
      logoUrl:"https://yt3.ggpht.com/ytc/AKedOLRDOZRDKSK-wzVzgXQv9bMMwAnKFgNG8rVtRgXpsQ=s88-c-k-c0x00ffffff-no-rj" ,
      videoId:"qksZcqogaLQ",
      description:"Vanilla Ice Cream is a mouth watering loved dessert and Learn how to make vanilla ice cream at home! This easy ice cream recipe needs only 3 ingredients. "},
    {  _id: uuid(),
      categoryName: "Cake",
      creator: "Masala Kitchen",
      videoUrl:"https://www.youtube.com/watch?v=pfsch-5d5f4",
      thumbnailUrl: "https://img.youtube.com/vi/pfsch-5d5f4/maxresdefault.jpg",
      title: "😍गारंटी है रुई जितना सॉफ्ट और स्पंजी केक घर की चीजों से | Super Soft Sponge Cake with Tips & Tricks",
      logoUrl:"https://yt3.ggpht.com/DaVa0ac-SAt3ELNHClQioSOJb-OB6TCV-MtZUQOfmbsw7gYC2hT308oBZyhBjP97oqxBDXSigg=s88-c-k-c0x00ffffff-no-rj" ,
      videoId:"pfsch-5d5f4",
      description:"Aaj Masala Kitchen me hum laye hain Super Soft Vanilla Sponge Cake. Cotton Soft Sponge Cake banega bahot hi easily aur Quick Sponge Cake Recipe aapko bahot pasand aayega. Vanilla Cake ghar par banane ka sabse aasan tarika aap is Sponge Cake Recipe Video me dekh sakte hain. Sirf 4 ingredients se banaye Cake jo banega bahot hi Soft & Fluffy Cake. Bina baking soda ke Sponge Cake banaye aur tasty Vanilla Cake bacchon ko bahot pasand aayega. Custard Cake Recipe ek baar zarur try kijiye. Eggless Sponge Cake banane ka isse aasan tarika aapne nahi dekha hoga. Easy Sponge Cake Recipe aap bana sakte hain bina oven ke perfect Cake. Instant Cake zarur banaiye aur is Eggless Cake Without Oven Recipe ko jyada se jyada share kijiye | Masala Kitchen | Recipes By Poonam Devnani"},
    {  _id: uuid(),
      categoryName: "Cake",
      creator: "Cook With Parul",
      videoUrl:"https://www.youtube.com/watch?v=m3e1n-0YxyI",
      thumbnailUrl: "https://img.youtube.com/vi/m3e1n-0YxyI/maxresdefault.jpg",
      title: "न चॉकलेट न क्रीम न अंडा ओवन मिंटो में सबसे आसन सस्ती बेकरी Easy Chocolate Cake | Best Chocolate Cake",
      logoUrl:"https://yt3.ggpht.com/ytc/AKedOLR5-XVBlTVuSs8wtgBOsJg2zPAtEZoClctsQqHvuQ=s88-c-k-c0x00ffffff-no-rj" ,
      videoId:"m3e1n-0YxyI",
      description:"Super Easy Chocolate cake without  Chocolate without cream No Egg No Oven Chocolate Cake Recipe in Kadahi without chaocolate or pressure cooker on Stove Top with Moist & Soft Choco Cake Frosting. This eggless chocolate cake recipe is a eggless Chocolate cake recipe . Learn How To Make Chocolate Cake Decorating So its become so Yummy chocolate cake. This is simple chocolate cake recipe moist chocolate cake and best chocolate cake . simple moist chocolate cake recipe always love by everyone.  Learn and cook Best Chocolate Cake Recipe this is a Easy Chocolate Cake Recipe Eggless and Without Oven Birthday Cake. The Most Amazing Chocolate Cake is full of moist, chocolatey perfection. This is the chocolate cake you’ve been dreaming of make easily in Kadahi Chocolate cake. Best Chocolate Cake Recipe, Easy Chocolate Cake Recipe, Eggless and Without Oven, Birthday Cake"},
    { _id: uuid(),
      categoryName: "Cake",
      creator: "CookingShooking ",
      videoUrl:"https://www.youtube.com/watch?v=HtX7f_dKWTw",
      thumbnailUrl: "https://img.youtube.com/vi/HtX7f_dKWTw/maxresdefault.jpg",
      title: "2 Min Mug Cake Recipe - Super Soft & Rich Eggless Microwave Cakes - CookingShooking",
      logoUrl:"https://yt3.ggpht.com/ytc/AKedOLQZa56MqK8ZLhHYY6orqWUPzzSlbIkOH94Tg95uFw=s88-c-k-c0x00ffffff-no-rj" ,
      videoId:"HtX7f_dKWTw",
      description:"In this video, we will cook together 2 minute mug cake recipes, this is a very easy and very tasty, rich and spongy eggless cake recipe, made right in microwave inside a mug. "},
      { _id: uuid(),
        categoryName: "Sweet Dish",
        creator: "Kunal Kapur",
        videoUrl:"https://www.youtube.com/watch?v=tjwdH3NFSaA",
        thumbnailUrl: "https://img.youtube.com/vi/tjwdH3NFSaA/maxresdefault.jpg",
        title: "Moong Dal Halwa | शादी वाला मूंग की दाल का हलवा | Winter Special Dessert | Chef Kunal Kapur Recipes",
        logoUrl:"https://yt3.ggpht.com/XDYDPAI6NqFMQeZv2PoysOfpxQV0qvtWZHVkkLnt70J7v8qoce0uZRyP6FucQPnWdDHN56S07g=s48-c-k-c0x00ffffff-no-rj" ,
        videoId:"tjwdH3NFSaA",
        description:"Method:Wash and soak moong dal for 4 hours. Drain the water. Add the dal to a grinder and grind it to a fine paste using Manual mode. Use little or no water to make the dal into a fine paste. Heat a pan add ghee. Add sooji and besan, cook on low heat till it turns light brown. Turn the heat to low and let the ghee cool down a bit. Now add the ground dal and stir. On very low heat cook the dal till it starts to brown. As the dal will get cooked it will get a sandy texture. In another pan add water, sugar, saffron and cardamom powder. Give a boil to dissolve the sugar and turn off the heat and remove. Once the dal is evenly browned add the sugar syrup. Cook till the dal absorbs all of the syrup. Add chopped nuts. Add grated khoya at this stage. Stir, remove and serve hot."},
        {
          _id: uuid(),
          categoryName: "Sweet Dish",
          creator: "Hebbars Kitchen",
          videoUrl:"https://www.youtube.com/watch?v=7uCqAtSVJU4",
          thumbnailUrl: "https://img.youtube.com/vi/7uCqAtSVJU4/maxresdefault.jpg",
          title: "Just 10 Minutes Dessert with few Ingredients | Instant & Easy Dessert Recipe",
          logoUrl:"https://yt3.ggpht.com/ytc/AKedOLSCB7LCbVXfDVLCFuphDPHfboJ0emo3TGaRtuuV=s88-c-k-c0x00ffffff-no-rj" ,
          description:
            "kaju katli recipe | kaju barfi recipe | kaju katli sweet | kaju ki barfi with detailed photo and video recipe. a popular indian sweet dessert recipe made with powdered cashew and sugar syrup. it is perhaps one of the popular indian sweet recipe which is made for all the celebrations, occasions and festival seasons. it is a simple and easy sweet snack recipe made with only 2 ingredients, but can be tricky with the sugar syrup consistency which may actually spoil the texture.kaju katli recipe | kaju barfi recipe | kaju katli sweet | kaju ki barfi with step by step photo and video recipe. dry fruits based sweets or desserts are very common recipes across india. it is generally made with just one choice of nuts, but can also be used as a combination of dry fruits to make a sugarless sweet snack. out of these the premium sweet recipe is the kaju katli recipe or the kaju barfi known for its mouth-watering and soothing texture and taste.",
        },
       
  ];

